// Configuration and constants for the Math Problems Dataset application

// Country flags mapping
const CONFIG = {
  /*** IMPORTANT: The small index file listing available countries ***/
  dataIndex: 'data/index.json', // e.g. ["Argentina","Saudi Arabia","China"]

  countryFlags: {
    "Afghanistan": "🇦🇫",
    "Albania": "🇦🇱",
    "Algeria": "🇩🇿",
    "Andorra": "🇦🇩",
    "Angola": "🇦🇴",
    "Antigua and Barbuda": "🇦🇬",
    "Argentina": "🇦🇷",
    "Armenia": "🇦🇲",
    "Australia": "🇦🇺",
    "Austria": "🇦🇹",
    "Azerbaijan": "🇦🇿",
    "Bahamas": "🇧🇸",
    "Bahrain": "🇧🇭",
    "Bangladesh": "🇧🇩",
    "Barbados": "🇧🇧",
    "Belarus": "🇧🇾",
    "Belgium": "🇧🇪",
    "Belize": "🇧🇿",
    "Benin": "🇧🇯",
    "Bhutan": "🇧🇹",
    "Bolivia": "🇧🇴",
    "Bosnia and Herzegovina": "🇧🇦",
    "Botswana": "🇧🇼",
    "Brazil": "🇧🇷",
    "Brunei": "🇧🇳",
    "Bulgaria": "🇧🇬",
    "Burkina Faso": "🇧🇫",
    "Burundi": "🇧🇮",
    "Cabo Verde": "🇨🇻",
    "Cambodia": "🇰🇭",
    "Cameroon": "🇨🇲",
    "Canada": "🇨🇦",
    "Central African Republic": "🇨🇫",
    "Chad": "🇹🇩",
    "Chile": "🇨🇱",
    "China": "🇨🇳",
    "Colombia": "🇨🇴",
    "Comoros": "🇰🇲",
    "Congo (Congo-Brazzaville)": "🇨🇬",
    "Costa Rica": "🇨🇷",
    "Croatia": "🇭🇷",
    "Cuba": "🇨🇺",
    "Cyprus": "🇨🇾",
    "Czechia": "🇨🇿",
    "Democratic Republic of the Congo": "🇨🇩",
    "Denmark": "🇩🇰",
    "Djibouti": "🇩🇯",
    "Dominica": "🇩🇲",
    "Dominican Republic": "🇩🇴",
    "Ecuador": "🇪🇨",
    "Egypt": "🇪🇬",
    "El Salvador": "🇸🇻",
    "Equatorial Guinea": "🇬🇶",
    "Eritrea": "🇪🇷",
    "Estonia": "🇪🇪",
    "Eswatini": "🇸🇿",
    "Ethiopia": "🇪🇹",
    "Fiji": "🇫🇯",
    "Finland": "🇫🇮",
    "France": "🇫🇷",
    "Gabon": "🇬🇦",
    "Gambia": "🇬🇲",
    "Georgia": "🇬🇪",
    "Germany": "🇩🇪",
    "Ghana": "🇬🇭",
    "Greece": "🇬🇷",
    "Grenada": "🇬🇩",
    "Guatemala": "🇬🇹",
    "Guinea": "🇬🇳",
    "Guinea-Bissau": "🇬🇼",
    "Guyana": "🇬🇾",
    "Haiti": "🇭🇹",
    "Honduras": "🇭🇳",
    "Hungary": "🇭🇺",
    "Iceland": "🇮🇸",
    "India": "🇮🇳",
    "Indonesia": "🇮🇩",
    "Iran": "🇮🇷",
    "Iraq": "🇮🇶",
    "Ireland": "🇮🇪",
    "Israel": "🇮🇱",
    "Italy": "🇮🇹",
    "Jamaica": "🇯🇲",
    "Japan": "🇯🇵",
    "Jordan": "🇯🇴",
    "Kazakhstan": "🇰🇿",
    "Kenya": "🇰🇪",
    "Kiribati": "🇰🇮",
    "Kuwait": "🇰🇼",
    "Kyrgyzstan": "🇰🇬",
    "Laos": "🇱🇦",
    "Latvia": "🇱🇻",
    "Lebanon": "🇱🇧",
    "Lesotho": "🇱🇸",
    "Liberia": "🇱🇷",
    "Libya": "🇱🇾",
    "Liechtenstein": "🇱🇮",
    "Lithuania": "🇱🇹",
    "Luxembourg": "🇱🇺",
    "Madagascar": "🇲🇬",
    "Malawi": "🇲🇼",
    "Malaysia": "🇲🇾",
    "Maldives": "🇲🇻",
    "Mali": "🇲🇱",
    "Malta": "🇲🇹",
    "Marshall Islands": "🇲🇭",
    "Mauritania": "🇲🇷",
    "Mauritius": "🇲🇺",
    "Mexico": "🇲🇽",
    "Micronesia": "🇫🇲",
    "Moldova": "🇲🇩",
    "Monaco": "🇲🇨",
    "Mongolia": "🇲🇳",
    "Montenegro": "🇲🇪",
    "Morocco": "🇲🇦",
    "Mozambique": "🇲🇿",
    "Myanmar (Burma)": "🇲🇲",
    "Namibia": "🇳🇦",
    "Nauru": "🇳🇷",
    "Nepal": "🇳🇵",
    "Netherlands": "🇳🇱",
    "New Zealand": "🇳🇿",
    "Nicaragua": "🇳🇮",
    "Niger": "🇳🇪",
    "Nigeria": "🇳🇬",
    "North Korea": "🇰🇵",
    "North Macedonia": "🇲🇰",
    "Norway": "🇳🇴",
    "Oman": "🇴🇲",
    "Pakistan": "🇵🇰",
    "Palau": "🇵🇼",
    "Palestine": "🇵🇸",
    "Panama": "🇵🇦",
    "Papua New Guinea": "🇵🇬",
    "Paraguay": "🇵🇾",
    "Peru": "🇵🇪",
    "Philippines": "🇵🇭",
    "Poland": "🇵🇱",
    "Portugal": "🇵🇹",
    "Qatar": "🇶🇦",
    "Romania": "🇷🇴",
    "Russia": "🇷🇺",
    "Rwanda": "🇷🇼",
    "Saint Kitts and Nevis": "🇰🇳",
    "Saint Lucia": "🇱🇨",
    "Saint Vincent and the Grenadines": "🇻🇨",
    "Samoa": "🇼🇸",
    "San Marino": "🇸🇲",
    "Sao Tome and Principe": "🇸🇹",
    "Saudi Arabia": "🇸🇦",
    "Senegal": "🇸🇳",
    "Serbia": "🇷🇸",
    "Seychelles": "🇸🇨",
    "Sierra Leone": "🇸🇱",
    "Singapore": "🇸🇬",
    "Slovakia": "🇸🇰",
    "Slovenia": "🇸🇮",
    "Solomon Islands": "🇸🇧",
    "Somalia": "🇸🇴",
    "South Africa": "🇿🇦",
    "South Korea": "🇰🇷",
    "South Sudan": "🇸🇸",
    "Spain": "🇪🇸",
    "Sri Lanka": "🇱🇰",
    "Sudan": "🇸🇩",
    "Suriname": "🇸🇷",
    "Sweden": "🇸🇪",
    "Switzerland": "🇨🇭",
    "Syria": "🇸🇾",
    "Tajikistan": "🇹🇯",
    "Tanzania": "🇹🇿",
    "Thailand": "🇹🇭",
    "Timor-Leste": "🇹🇱",
    "Togo": "🇹🇬",
    "Tonga": "🇹🇴",
    "Trinidad and Tobago": "🇹🇹",
    "Tunisia": "🇹🇳",
    "Turkey": "🇹🇷",
    "Turkmenistan": "🇹🇲",
    "Tuvalu": "🇹🇻",
    "Uganda": "🇺🇬",
    "Ukraine": "🇺🇦",
    "United Arab Emirates": "🇦🇪",
    "United Kingdom": "🇬🇧",
    "United States": "🇺🇸",
    "Uruguay": "🇺🇾",
    "Uzbekistan": "🇺🇿",
    "Vanuatu": "🇻🇺",
    "Vatican City": "🇻🇦",
    "Venezuela": "🇻🇪",
    "Vietnam": "🇻🇳",
    "Yemen": "🇾🇪",
    "Zambia": "🇿🇲",
    "Zimbabwe": "🇿🇼",
    "IMO": "🌍" // International Maritime Organization / fallback
  },

    // Default filter values
    defaultFilters: { type: 'all', language: 'all', search: '' },

    // UI settings
    ui: { loadingDelay: 100, animationDuration: 300 },

    // Sample data fallback (for development/demo purposes)
    sampleData: {
        "Saudi Arabia": {
            "2012": [
                {
                    "statement_latex": "Find all positive integers $n$ such that $5^n + 7$ is divisible by 6.",
                    "author": "Dr. Fawzi A. Al-Thukair",
                    "solutions": [],
                    "id": "p_9e7a871c04c5",
                    "statement_images": [],
                    "booklet title": "Saudi Arabia booklet 2012.pdf",
                    "page numbers": [0],
                    "language": "ar",
                    "competition name": "International Mathematics Olympiad; Asian Pacific Olympiad; Balkan Mathematical Olympiad",
                    "booklet_url": "https://drive.google.com/open?id=1Nh1vmkPNnqQpJd-x8bfeeB-b9IHBU2nO",
                    "has_solutions": true,
                    "copyright_info": "NULL",
                    "_provenance": {
                        "folder": "SAU_2012",
                        "pages_map": {
                            "P0": "page61.md",
                            "P1": "page62.md",
                            "P2": "page63.md"
                        }
                    }
                }
            ]
        },
        "Argentina": {
            "2013": [
                {
                    "statement_latex": "Two circles and of different radii intersect at two points *A* and *B*, let *C* and *D* be two points on and , respectively, such that *A* is the midpoint of the segment *CD*. The extension of *DB* meets at another point *E*, the extension of *CB* meets at another point *F*. Let and be the perpendicular bisectors of *CD* and *EF*, respectively. \n\n(1) Show that and have a unique common point (denoted by **P**). \n(2) Prove that the lengths of *CA*, *AP* and *PE* are the side lengths of a right triangle.\n\n% IMAGE: ![Problem diagram](images/Kina_2013_p2_data_3975839a74.png)",
                    "author": "NULL",
                    "solutions": [
                        {
                            "pages": ["P0"],
                            "latex": "Add up the numbers on each segment. By hypothesis this gives 6 equal sums, say equal to S. Since each $a_i$ enters exactly two of these sums, we obtain $6S = 2(1+2+\\dots+12)$, $S = 26$. Thus the 4 numbers on each segment have sum 26.",
                            "status": "complete",
                            "images": []
                        }
                    ],
                    "id": "p_2cdcde4bf601",
                    "statement_images": [
                        {
                            "title": "",
                            "alt": "",
                            "path": "images/3._NATIONAL_XXX_OMA_2013-checkpoint_p1_data_538915404d.png",
                            "pages": ["P0"]
                        }
                    ],
                    "booklet title": "3. NATIONAL XXX OMA 2013.pdf",
                    "page numbers": [0],
                    "language": "en",
                    "competition name": "XXX OMA",
                    "booklet_url": "https://drive.google.com/open?id=1xN8tAqrMuDa_yP31PJwm_SMyW-DpvBvw",
                    "has_solutions": true,
                    "copyright_info": "NULL",
                    "_provenance": {
                        "folder": "3. NATIONAL XXX OMA 2013-checkpoint",
                        "pages_map": {
                            "P0": "page7.md",
                            "P1": "page8.md",
                            "P2": "page9.md"
                        }
                    }
                }
            ]
        }
    }
};

// Export for modules (if using ES6 modules in the future)
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CONFIG;
}